version: 0.0
os: linux
files:
   - source: /
     destination: /usr/share/tomcat7/webapps
permissions:
   - object: /usr/share/tomcat7/webapps
     pattern: "**"
     owner: tomcat
     group: tomcat
     mode: 755
     type:
       - file
