version: 0.1
phases:
  install:
    commands:
      - apt-get install -y zip
  build:
    commands:
      - cd myapp && mvn clean install && cd target && zip myapp.war.zip myapp.war 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
   files:
     - '**/*.zip'
   discard-paths: yes
